### ISSUE TITLE
Scrolling automatically

### ISSUE THREAD

**Issue by tomasmalio** [jonmbake/react-terminal-ui#51]
**Describe the bug**
I'm creating a platform with the terminal, and I'd include the component at the bottom of the website when we enter the first time the platform scrolls to the position of the terminal. I tried to fixed with the `overflow-anchor: none` but didn't work.

**To Reproduce**
1. Create a website with different sections that needs to scroll to the position of you're `react-terminal-ui`
2. Load the website
3. The website is going to scroll automatically to the terminal.

**Expected behavior**
I don't want this to automatically scroll to the terminal. How can I configure it to avoid this?

**Comment by jonmbake** [comment]
Hey @tomasmalio . Right now the terminal is setup so the terminal cursor scrolls into view (so the user always sees the cursor). We may be able to change it so the scroll into view is localized to the terminal container. Feel free to submit a PR for the change.

**Comment by jonmbake** [comment]
@tomasmalio This is available in v1.3.0.

**Comment by tomasmalio** [comment]
HI @jonmbake I'm checking if everything works because right now in my app doesn't work

**Comment by jonmbake** [comment]
@tomasmalio What browser are you using? I'm not seeing the behavior you described when testing in Firefox 125.0.3 on MacOs. Created a 1000px height div and a terminal below (off screen). When I load the page, it does not scroll to the terminal:

<img width="415" alt="Screenshot 2024-05-11 at 3 17 19 PM" src="https://github.com/jonmbake/react-terminal-ui/assets/865534/fa42c0f2-4ff2-44fd-a3ad-15e4e3f8d30a">

Also, I should have more closely reviewed the code change... The scroll into view only happens on key press so the code change you made is likely unnecessary. I suspect maybe the browser you are testing in auto-scrolls to focused input on page load; the issue is likely with the `autoFocus={ onInput != null }` bit.

**Comment by tomasmalio** [comment]
Hi @jonmbake, I'm testing in MacOS with Chrome 124.0.6367.119.

I tried to do it with the autoFocus, but it also goes to the terminal. I'm trying to understand why.

**Comment by tomasmalio** [comment]
@jonmbake I have tried multiple ways, but I have not succeeded. Keep scrolling.
I have developed a platform with react js, and when it initializes, it directs me to where the terminal is.

**Comment by jonmbake** [comment]
@tomasmalio Is your platform/website publicly accessible? Can you email me the URL? I would like to take a look at the behavior. I'm not able to reproduce it locally.

Also, did you try disabling `autofocus` from the terminal code? Did it have an effect?
